# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
#  docker-compose -f postgresql-compose.yml up
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    restart: always
volumes:
  dbdata: